# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Eng.Mohamed/Desktop/DSD_Project_Final_Version/DSD_Project_Final_Version.cache/wt [current_project]
set_property parent.project_path C:/Users/Eng.Mohamed/Desktop/DSD_Project_Final_Version/DSD_Project_Final_Version.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Eng.Mohamed/Desktop/DSD_Project_Final_Version/DSD_Project_Final_Version.srcs/sources_1/new/Temp_Sensor.vhd
  C:/Users/Eng.Mohamed/Desktop/DSD_Project_Final_Version/DSD_Project_Final_Version.srcs/sources_1/new/Segment_Control.vhd
  C:/Users/Eng.Mohamed/Desktop/DSD_Project_Final_Version/DSD_Project_Final_Version.srcs/sources_1/new/Ultrasonic_Sensor.vhd
  C:/Users/Eng.Mohamed/Desktop/DSD_Project_Final_Version/DSD_Project_Final_Version.srcs/sources_1/new/LEDs_Control.vhd
  C:/Users/Eng.Mohamed/Desktop/DSD_Project_Final_Version/DSD_Project_Final_Version.srcs/sources_1/new/Main.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Eng.Mohamed/Desktop/Basys-3-Master.xdc
set_property used_in_implementation false [get_files C:/Users/Eng.Mohamed/Desktop/Basys-3-Master.xdc]


synth_design -top Main -part xc7a35tcpg236-1


write_checkpoint -force -noxdef Main.dcp

catch { report_utilization -file Main_utilization_synth.rpt -pb Main_utilization_synth.pb }
